### ISSUE TITLE
Overwriting LUTs for PlanetScope, causing lutnc not found 

### ISSUE THREAD

**Issue by yulunmaps** [acolite/acolite_mr#1]
Hi! The existing LUT 'PONDER-LUT-201704-MOD1-1013mb' in acolite_mr.py overwrites 'PONDER-LUT-201704-MOD1' in planetscaope_ac.py. This makes the lutid, in the file name, 'PONDER-LUT-201704-MOD1-1013mb-0500mb' after appending an additional '-500mb' to it. The script fails because the LUT file's path, lutnc, can not be found. 

Would removing 'luts=luts' in line 83 in acolite_mr_ac.py be a good solution?

**Comment by acolite** [comment]
Indeed the PlanetScope processing should use the new way of interpolating the LUTs, where including the pressure in the LUT name is no longer needed. I think the latest commit takes care of that, with some issue perhaps with the old sky reflectance correction. There will be a new sky reflectance correction in an upcoming update.
