### ISSUE TITLE
Support for VENµS data

### ISSUE THREAD

**Issue by ffilipponi** [acolite/acolite_mr#4]
Dear developers,

I am wondering if the acolite_mr support for VENµS data, available at Theia CNES repository, is planned among future developments.

Regards,

Federico Filipponi

**Comment by acolite** [comment]
Hi Federico

Thanks for your pull request with some fixes! Up until the moment of your question I had no plans to include VENµS data, but now you have raised my interest. :-) I am downloading one file at the moment, but if you have a specific scene you are interested in, please let me know!

Quinten

**Comment by ffilipponi** [comment]
Hi Quinten,

thank you for considering the support for VENµS data and for prompt reply.
I do not have a specific scene in mind, I would just have to possibility to use ACOLITE MR to correct VENµS data.

Ciao,

Federico

**Comment by acolite** [comment]
I have released a beta version of the generic ACOLITE with Venµs support! 

https://odnature.naturalsciences.be/remsem/acolite-forum/viewtopic.php?f=3&t=251

https://github.com/acolite/acolite

Let me know what you find!

Quinten
